# Generated by Django 2.2.7 on 2019-11-12 12:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_description', models.TextField()),
                ('asset_tag', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('present_location', models.CharField(max_length=100)),
                ('new_destination', models.CharField(max_length=100)),
                ('asset_make', models.CharField(max_length=100)),
                ('asset_model', models.CharField(max_length=100)),
                ('asset_serial_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason_for_movement', models.TextField()),
                ('requestor_unit', models.CharField(max_length=100)),
                ('requestor_branch', models.CharField(max_length=100)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.CharField(max_length=100)),
                ('collector_phone_number', phone_field.models.PhoneField(blank=True, help_text='Collector phone number', max_length=31)),
                ('collector_company', models.CharField(max_length=100)),
                ('collector_branch', models.CharField(max_length=100)),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
